spring:
  application:
    name: storage-service
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.45.100:3306/storage?useSSL=false
      username: root
      password: 123456
  jpa:
    show-sql: true
server:
  port: 18081
logging:
  level:
    com:
      alibaba: debug
      example:
        demo: debug
    org:
      springframework:
        cloud:
          alibaba: debug