spring:
  application:
    name: business-service
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
server:
  port: 18084
logging:
  level:
    com:
      alibaba: debug
      example:
        demo: debug
    org:
      springframework:
        cloud:
          alibaba: debug